export const types = {
  uiOpenModal: "[ui] Open Modal",
  uiCloseModal: "[ui] Close Modal",
  eventLogout: "[event] Event logout",
  eventSetActive: "[event] Set active",
  eventStartNew: "[event] Start event new",
  eventAddNew: "[event] Add new",
  clearActiveEvent: "[event] Clear active event",
  eventUpdate: "[event] Event update",
  eventDelete: "[event] Event delete",
  eventLoaded: "[event] Event loaded",
  authCheckin: "[auth] Cheking login state",
  authCheckinFinish: "[auth] Finish login state",
  authStartLogin: "[auth] Start login",
  authLogin: "[auth] Login",
  authStartRegister: "[auth] Start register",
  authStartTokenRenew: "[auth] Start token renew",
  authLogout: "[auth] Logout",
};
